# Generated by Django 4.2.3 on 2023-07-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='productor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda_app.productor'),
            preserve_default=False,
        ),
    ]
